---
- set_fact:
    tmp_path: /tmp/install_ctakes.sh

- name: Copies ctakes installation script to remote hosts
  copy:
    src: install_ctakes.sh
    dest: "{{ tmp_path }}" 
    mode: 0755

- name: Runs ctakes installation script
  command: "{{ tmp_path }} -c 2 -u 4 -r"
  become: yes
  register: ctakes_out

- debug:
    var: ctakes_out

