- hosts: all
  pre_tasks:
  - name: Gathers facts from ALL hosts (regardless of limit or tags)
    setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ groups['all'] }}"  
