---
- import_playbook: install.yml

- import_playbook: configure.yml

- hosts: journalnodes
  tasks:
  - include_role:
      name: hdfs
      tasks_from: start-journalnode.yml

- hosts: namenodes[0]
  tasks:
  - include_role:
      name: hdfs
      tasks_from: format-cluster.yml
  - include_role:
      name: hdfs
      tasks_from: start-namenode.yml

- hosts: namenodes[1]
  tasks:
  - include_role:
      name: hdfs
      tasks_from: bootstrap-standbynamenode.yml
  - include_role:
      name: hdfs
      tasks_from: start-namenode.yml

- hosts: namenodes[0]
  tasks:
  - include_role:
      name: hdfs
      tasks_from: set-namenode-to-active.yml

- hosts: datanodes
  tasks:
  - include_role:
      name: hdfs
      tasks_from: conf-datanode.yml
  - include_role:
      name: hdfs
      tasks_from: start-datanode.yml

- hosts: namenodes[0]
  tasks:
  - include_role:
      name: hdfs
      tasks_from: users.yml
    vars:
      new_hdfs_users:
        - user: cades
          group: users
          quota: 20g

- hosts: yarnservers[0]
  tasks:
  - include_role:
      name: hdfs
      tasks_from: start-yarn.yml
    when: hdfs_use_yarn == True

- hosts: yarnservers[1]
  tasks:
  - block:
    - include_role:
        name: hdfs
        tasks_from: start-yarn-resourcemanager.yml
    - include_role:
        name: hdfs
        tasks_from: start-yarn-webappproxy.yml
    when: hdfs_use_yarn == True
