- block:
  - set_fact:
      tmp_file: /tmp/etc_hosts
  
  - name: Creates "{{ tmp_file }}" file
    file:
      path: "{{ tmp_file }}"
      state: touch 

  - name: Adds header to {{ tmp_file }} file
    copy:
      dest: "{{ tmp_file }}"
      content: | 
        127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
        ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
        
  - debug:
      msg: "{{ groups.all }}" 

  - name: Populates {{ tmp_file }} file
    lineinfile: 
      dest: "{{ tmp_file }}" 
      line: "{{ hostvars[item].inventory_hostname }}      {{ hostvars[item].ansible_hostname }}"
    with_items: "{{ groups.all }}"
  delegate_to: localhost
  run_once: yes

- name: Copies host file to all nodes
  copy:
    src: "{{ tmp_file }}"
    dest: /etc/hosts
    owner: root
    group: root
  become: yes
  become_user: root

