---
- name: Installs latest openjdk-devel
  package: 
    name: java-1.8.0-openjdk-devel
    state: present 
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: Installs latest openjdk-8-jdk
  package: 
    name: openjdk-8-jdk
    state: present 
  when: ansible_os_family == "Debian"

- name: Sets JAVA_HOME
  template:
    src: etc/profile.d/java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
