---
- block:
  - name: Downloads the atop rpm
    get_url:
      url: ftp://172.22.4.129/pub/atop-2.3.0-1.el7.x86_64.rpm
      dest: /tmp/atop-2.3.0-1.el7.x86_64.rpm

  - name: Yum installs atop 
    yum: 
      name: /tmp/atop-2.3.0-1.el7.x86_64.rpm
      state: present
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: Installs atop 
  package: 
    name: atop 
    state: present
  when: ansible_os_family == "Debian"

- name: Starts atop service
  service:
    name: atop
    state: started
    enabled: yes

- name: Installs packages
  package: 
    name: ['screen', 'tmux', 'bzip2', 'unzip', 'lsof', 'tar','gawk', 'bc', 'wget']
    state: present 
