---
- block:
  - name: Installs yum-utils 
    yum: 
      name: yum-utils 
      state: present
  
  - name: Installs development tools 
    yum: 
      name: "@Development tools" 
      state: present
  
  - name: Installs Python rpm 
    yum: 
      name: https://centos7.iuscommunity.org/ius-release.rpm
      state: present
  
  - name: Installs Python packages 
    yum: 
      name: ["python36u", "python36u-pip", "python36u-devel"] 
      state: present
  
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
  become: yes
  become_user: root

- name: Installs latest python 
  package: 
    name: python36u 
    state: present 
  when: ansible_os_family == "Debian"

