- include_role:
    name: common
- include_role: 
    name: hdfs-common
    tasks_from: common.yml
- include_role: 
    name: alluxio 
    tasks_from: common.yml
- include_role:
    name: hbase 
    tasks_from: common.yml
- include_role:
   name: phoenix
   tasks_from: common.yml 
- include_role:
    name: zookeeper
    tasks_from: common.yml
- include_role:
    name: solr
    tasks_from: common.yml
- include_role:
    name: elasticsearch 
    tasks_from: common.yml
