---
- include_tasks: include_role_vars.yml

- name: Stores role path for current role
  set_fact:
    hdfs_role_path: "{{ role_path }}"
    
- name: Performs standard HDFS installation from tarball  
  include_role:
    name: util
    tasks_from: standard-install.yml
  vars:
    args_parent_role_path: "{{ hdfs_role_path }}"
    args_unix_user: "{{ hdfs_unix_user }}"
    args_unix_group: "{{ hadoop_group_name }}"
    args_unix_home: "{{ hdfs_unix_home }}"
    args_generate_ssh_key: yes 
    args_checksum: "{{ hdfs_checksum }}"
    args_tar_name: "{{ hdfs_tar_name }}"
    args_install_dir_version: "{{ hdfs_install_dir_version }}"
    args_install_dir: "{{ hdfs_install_dir }}"
    args_conf_dir: "{{ hdfs_conf_dir }}"
    args_log_dir: "{{ hdfs_log_dir }}"
    args_pid_dir: "{{ hdfs_pid_dir }}"
    args_data_dir: "{{ hdfs_data_dir }}"
