---
- name: Shares SSH keys between namenodes
  include_role: 
    name: util
    tasks_from: keys.yml
  vars:
    key_source_hosts: "{{ groups['namenodes'] }}"
    key_target_hosts: "{{ groups['namenodes'] }}"
    key_user: "{{ hdfs_unix_user }}" 
    key_user_unix_home: "{{ hdfs_unix_home }}"
  
- name: Creates a namenode data directory 
  file: 
    path: "{{ dfs_namenode_name_dir }}"
    state: directory
    owner: "{{ hdfs_unix_user }}"
    group: "{{ hadoop_group_name }}"
    mode: 0755
  become: yes
  become_user: root

- name: Creates the namenode systemd service file
  template:
    src: etc/systemd/system/namenode.service.j2
    dest: /etc/systemd/system/namenode.service
  become: yes
  become_user: root
