---
- name: Sets Hadoop configuration files 
  template:
    src: "{{ item }}.j2"
    dest: "{{ hdfs_conf_dir }}/{{ item }}"
    owner: hdfs
    group: "{{ hadoop_group_name }}"
    mode: 0644
  with_items:
   - hadoop-env.sh
   - core-site.xml
   - hdfs-site.xml
  become: yes
  become_user: hdfs

- name: Sets HADOOP_PREFIX and HADOOP_CONF_DIR 
  template:
    src: etc/profile.d/hdfs.sh.j2
    dest: /etc/profile.d/hdfs.sh
    mode: 0644
  become: yes
