---
- name: Transitions a namenode to active state from standby
  block:
    - name: Checks the current state
      command: "{{ hadoop_prefix }}/bin/hdfs haadmin -getServiceState nn1"
      register: current_state
    - name: Transitions to active
      command: "{{ hadoop_prefix }}/bin/hdfs haadmin -transitionToActive nn1"
      when: current_state.stdout == 'standby'
  environment:
    JAVA_HOME: "{{ java_home }}"
    HADOOP_PREFIX: "{{ hadoop_prefix }}"
    HADOOP_YARN_HOME: "{{ hadoop_prefix }}"
    HADOOP_CONF_DIR: "{{ hdfs_conf_dir }}"
  become: yes
  become_user: hdfs
