- name: Starts YARN WebAppProxy server
  command: "{{ hdfs_install_dir }}/sbin/yarn-daemon.sh --config {{ hadoop_conf_dir }} start proxyserver"
  args:
    creates: "{{ yarn_pid_dir }}/yarn-yarn-resourcemanager.pid"
  become: yes
  become_user: "{{ hdfs_unix_user }}"
  environment:
    YARN_LOG_DIR: "{{ yarn_log_dir }}"
    YARN_PID_DIR: "{{ yarn_pid_dir }}"
