---
- name: Sets unlimited number of files for MEMLOCK
  pam_limits:
    domain: "{{ hdfs_unix_user }}"
    limit_type: "-" 
    limit_item: memlock
    value: unlimited
    comment: "unlimited memory lock for {{ hdfs_unix_user }}"
  become: yes
  become_user: root

- name: Starts an HDFS Datanode daemon
  command: "{{ hadoop_prefix }}/sbin/hadoop-daemon.sh --config {{ hadoop_conf_dir }} --script hdfs start datanode"
  args:
    creates: "{{ dfs_datanode_data_dir }}/in_use.lock"
  become: yes
  become_user: hdfs

# - name: Starts HDFS datanode service
#   systemd:
#     name: datanode
#     state: started
#     enabled: no 
#     daemon_reload: yes
#   become: yes
#   become_user: root
#   when: False
