---
- name: Starts HDFS NameNode daemon
  command: |
    {{ hadoop_prefix }}/sbin/hadoop-daemon.sh --config 
    {{ hadoop_conf_dir }} --script hdfs start namenode
  args:
    creates: "{{ dfs_namenode_name_dir }}/in_use.lock"
  environment:
    JAVA_HOME: "{{ java_home }}"
  become: yes
  become_user: "{{ hdfs_unix_user }}"

- name: Starts HDFS namenode service
  systemd:
    name: namenode
    state: started
    enabled: no 
    daemon_reload: yes
  become: yes
  become_user: root
  when: False
