---
- block:
  - name: Creates a volume for storing software source tarballs
    os_volume:
      state: present
      size: 4 
      display_name: tarball-store 
      snapshot_id: 3d313af2-c5e7-4708-bb70-ca16fed4ff8d 

  - name: Attaches the file repo volume to the ansible controller on localhost
    os_server_volume:
      state: present
      server: ansible 
      volume: tarball-store 
      device: /dev/vdb

  - name: Performs sudo fs operations
    block:
    - name: Creates xfs filesystem on /dev/vdb
      filesystem:
        fstype: xfs
        dev: /dev/vdb
        opts:

    - name: Mounts the volume once attached 
      mount:
        path: /mnt/tarball-store
        src: /dev/vdb
        fstype: xfs 
        state: mounted 
      
    - name: Makes cades user owner of /mnt/tarball-store 
      file:
        path: /mnt/tarball-store
        state: directory
        owner: cades 
    become: yes
    become_user: root
  delegate_to: localhost
  run_once: yes
