---
- block:
  - name: Includes role variables 
    include_vars:
      dir: '.'
    
  - name: Deletes an server {{ server_name }} 
    os_server:
      state: absent
      terminate_volume: yes
      wait: yes
      name: "{{ server_name }}"
      auth: "{{ openstack_auth }}"
  delegate_to: localhost
  run_once: yes
