---
- name: Includes role variables 
  include_vars:
    dir: '.'
  
- name: Create an instance {{ instance_name }} from image type {{ image }}
  os_server_facts:
    server: "{{ instance_name }}"
    auth: "{{ openstack_auth }}"
  delegate_to: localhost
  run_once: yes
  register: os_output

- debug:
    msg: "{{ item.name }}"
  with_items:
    - "{{ openstack_servers }}"
    
- debug:
    msg: "{{ item.addresses.or_provider_general_intnetwork1[0].addr }}"
  with_items:
    - "{{ openstack_servers }}"
