---
- block:
  - name: Includes role variables 
    include_vars:
      dir: '.'

  - name: Gets the first volume id attached to {{ server_name }} 
    os_server_facts:
      server: "{{ server_name }}"
      auth: "{{ openstack_auth }}"
    
  - set_fact:
      volume_id: "{{ openstack_servers[0]['volumes'][0]['id'] }}"
      
  - debug:
      msg: "{{ volume_id }}"

  - name: Stops the server instance {{ server_name }} to ensure consistency
    os_server_action:
      server: "{{ server_name }}"
      action: stop
      auth: "{{ openstack_auth }}"

  - name: Snapshots the volume {{ volume_id }} 
    os_volume_snapshot: 
      name: "{{ server_name }}-volume-snapshot"
      volume: "{{ volume_id }}"
      state: present
      description: "Volume snapshot for {{ server_name }}"
      auth: "{{ openstack_auth }}"
      force: yes
      
  - name: Restarts the server instance {{ server_name }} 
    os_server_action:
      server: "{{ server_name }}"
      action: start 
      auth: "{{ openstack_auth }}"
      
  delegate_to: localhost
  run_once: yes
