---
- block:
  - name: Installs spaCy for CPU 
    conda:  
      name: spacy
      state: latest 
      channels: conda-forge 
      executable: "{{ anaconda_install_dir }}/bin/conda"
    
  - name: Installs PyTorch and torchvision
    conda: 
      name: "{{ item }}"
      state: latest 
      channels: pytorch
      executable: "{{ anaconda_install_dir }}/bin/conda"
    with_items:
      - pytorch
      - torchvision

  - name: Installs Elasticsearch client 
    pip:  
      name: elasticsearch 
      version: 6.1.1
      state: present 
      executable: "{{ anaconda_install_dir }}/bin/pip"
  become: yes
  become_user: anaconda
