---
- hosts: localhost
  tasks:
  - name: Creates openstack uber-client server 
    include_role: 
      name: openstack
      tasks_from: create-server.yml
    vars: 
      server_name: uber-client
      flavor: "c1.tiny"
      image: "CADES_CentOS-7.4_v20180123_1"
      boot_from_volume: yes 
      volume_size: 12 
  - name: Refresh the ansible in-memory inventory 
    meta: refresh_inventory
  - wait_for:
      host: "{{ hostvars['uber-client']['ansible_ssh_host'] }}"
      port: 22
      state: started
      connect_timeout: 5
      timeout: 30 

- hosts: uber-client
  tasks:
  - include_role:
      name: common 
      tasks_from: uber-client-common.yml

- hosts: localhost
  tasks:
  - name: Creates openstack uber-client server snapshot 
    include_role: 
      name: openstack
      tasks_from: snapshot-volume.yml
    vars: 
      server_name: uber-client
      snapshot_name: uber-client-snapshot
      description: "A server snapshot of the uber-client server"
  - name: Deletes the openstack uber-client server
    include_role:
      name: openstack
      tasks_from: delete-server.yml
    vars:
      server_name: uber-client
