---
- block:
  - name: "Ensures group {{ group }} is present"
    group:
      name: "{{ group }}"
      state: present

  - name: "Adds new unix user {{ user }}" 
    user: 
      name: "{{ user }}"
      groups: "{{ group }}" 
      state: present 
      shell: /bin/bash
      createhome: yes 
      home: "{{ home }}"
      generate_ssh_key: "{{ generate_ssh_key }}"  

  - name: "Sets permissions of {{ user }}'s home directories"
    file: 
      path: "{{ home }}" 
      owner: "{{ user }}"
      group: "{{ group }}" 
      mode: 0755
      state: directory 
  become: yes
  become_user: root
