- name: Checks if swap is being used
  command: swapon -s
  register: swap_status
  become: yes

- debug:
    var: swap_status

- block:
  
  - name: Creates swap file
    command: dd if=/dev/zero of=/swapfile count=4096 bs=1MiB 
    args:
      creates: /swqpfile

  - name: Enables swap file
    file:
      path: /swapfile
      mode: 0600

  - name: Sets up the swap space for use 
    command: mkswap /swapfile

  - name: Sets up the swap space for use 
    command: swapon /swapfile

  when: swap_status.stdout == ""
  become: yes
