- block:
  - name: Installs NFS packages 
    package:
      name: nfs-utils 
      state: present

  - name: Creates mount point directory
    file:
      path: /mnt/nfsshare
      mode: 0777
      state: directory

  - name: Mounts NFS
    mount:
      path: /mnt/nfsshare
      src: "or-nas-v218-volume-01-vip.ornl.gov:/volumes/warpfs/nomount/volume-01/cades-va"
      state: mounted 
      fstype: nfs
      opts: auto,intr,tcp,nfsvers=3,noatime

  - name: Creates the host directory on NFS
    file:
      path: "/mnt/nfsshare/{{ ansible_hostname }}/data"
      recurse: yes
      state: directory
  
  - name: Links the data directory
    file:
      src: "/mnt/nfsshare/{{ ansible_hostname }}/data"
      dest: "{{ data_dir }}" 
      state: link 
  become: yes
